name: Deployment - Efficent

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Build code
        run: npm run build

      - name: Deploy
        run: echo "Deploying project"
